#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
This program will move your robot forward for 2 seconds. At the end of the program, all motors
will shut down automatically and turn off.

ROBOT CONFIGURATION: LEGO EV3 REM Bot
MOTORS & SENSORS:
[I/O Port]          [Name]              [Type]                			[Location]
MotorC        			leftMotor           LEGO EV3 Motor		      Left side motor
MotorB       				rightMotor          LEGO EV3 Motor		      Right side motor (reversed)
------------------------------------------------------------------------------------------------*/

task main()
{
	//forward(1,rotations,100);
	for (int i =0; i<3;i++)
	{
		setMotorSyncEncoder(leftMotor, rightMotor, 0, 2170, 50);//move 1m

		setMotorSyncEncoder(leftMotor,rightMotor, 100, 250, 25);//turn 90
	}


	//sleep(2000);										//Wait for 2 seconds before continuing on in the program.
}
