#pragma config(Sensor, S1,     ultrasonicSensor, sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     colourSensor,   sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     gyroSensor,     sensorNone)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorB,          grabberMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorD,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int colour;
int releaser;

task colourCheck(){
	while(1){
		colour = getColorName(colourSensor);
	}
}

void time(){
	displayBigTextLine(5,"IN TIME");
	sleep(5000);
	releaser = 1;
	displayBigTextLine(1,"%d", releaser);
}

task main()
{
	startTask(colourCheck);

	while(1){
		displayBigTextLine(3,"%d", colour);
		setMotorSync(leftMotor,rightMotor,0,25);

		displayBigTextLine(1,"%d", releaser);
		if (colour ==5 && releaser ==0){
			setMotorSync(leftMotor,rightMotor,0,0);
			playSound(soundBeepBeep);
			time();
			displayBigTextLine(5,"OUT OF TIME");
					releaser = 0;
		  setMotorSyncEncoder(leftMotor, rightMotor, 0, 500, -25);
		  waitUntilMotorStop(leftMotor);
		}
	}
}
