#pragma config(Sensor, S1,     ultrasonicSensor, sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     colourSensor,   sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     gyroSensor,     sensorNone)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorB,          grabberMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorD,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void forward2rotations(){
	resetMotorEncoder(leftMotor);//reset measurement
	resetMotorEncoder(rightMotor);//reset measurement
	setMotorSyncEncoder(leftMotor, rightMotor, 0, 720, 25);//forward 2 rotations 720 deg
	waitUntilMotorStop(leftMotor);//wait
	waitUntilMotorStop(rightMotor);//wait
}

void forward90deg(){
	resetMotorEncoder(leftMotor);//reset measurement
	resetMotorEncoder(rightMotor);//reset measurement
	setMotorSyncEncoder(leftMotor, rightMotor, 0, 90, 25);//forward 90 deg
	waitUntilMotorStop(leftMotor);//wait
	waitUntilMotorStop(rightMotor);//wait

}

void forward2Sec(){
	setMotorSyncTime(leftMotor, rightMotor, 0, 2000, 25);
	waitUntilMotorStop(leftMotor);//wait
	waitUntilMotorStop(rightMotor);//wait
}

void chonk(){
	resetMotorEncoder(leftMotor);//reset measurement
	resetMotorEncoder(rightMotor);//reset measurement
	setMotorSyncEncoder(leftMotor, rightMotor, 0, 1800, 10);//forward 2 rotations 720 deg
	waitUntilMotorStop(leftMotor);//wait
	waitUntilMotorStop(rightMotor);//wait


	resetMotorEncoder(leftMotor);//reset measurement
	resetMotorEncoder(rightMotor);//reset measurement
	setMotorSyncEncoder(leftMotor, rightMotor, 0, 1800, -100);//forward 2 rotations 720 deg
	waitUntilMotorStop(leftMotor);//wait
	waitUntilMotorStop(rightMotor);//wait
}


void spin(){
	int gyro =0;
	resetGyro(gyroSensor);
	while(gyro < 360){
		setMotorSpeed(leftMotor, 50);
		setMotorSpeed(rightMotor,0);
		gyro = fabs(getGyroDegrees(gyroSensor));
		}
}

task main()
{
	spin();


}
