#pragma config(Sensor, S1,     ultrasonicSensor, sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     colourSensor,   sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     gyroSensor,     sensorNone)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorB,          grabberMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorD,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int ultrasonic =0;
task distanceSensor(){
	while(1){
		ultrasonic = getUSDistance(S1);
}}

task main()
{
	startTask(distanceSensor);
	while(1){
		displayBigTextLine(3, "distance %d",ultrasonic);
		if (ultrasonic > 50){
			setMotorSpeed(rightMotor, 100);
			setMotorSpeed(leftMotor, 100);
		}

		if ((ultrasonic <50) && (ultrasonic  >25)){
			setMotorSpeed(rightMotor, 50);
			setMotorSpeed(leftMotor, 50);
		}


		if ((ultrasonic<25) && (ultrasonic >7)){
			setMotorSpeed(rightMotor, 20);
			setMotorSpeed(leftMotor, 20);
		}

		if (ultrasonic <7){
			setMotorSpeed(rightMotor, 5);
			setMotorSpeed(leftMotor, 5);
		}

		if (ultrasonic== 7){
			setMotorSpeed(rightMotor, 0);
			setMotorSpeed(leftMotor, 0);
		}
	}
}
