#pragma config(Sensor, S1,     ultrasonicSensor, sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colourSensor,   sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorB,          grabberMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorD,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int intencity = 0;
int prevIntencity;

int position;

//Reflected light intencity

/*task colourCheck(){
while(1){}
}*/

/*task gyroCheck(){
resetGyro(gyroSensor);
position =getGyroDegrees(S2);
}*/



task main()
{

	bool leftRight = false;
	//startTask(colourCheck);
	//startTask(gyroCheck);
	setMotorSpeed(leftMotor, 25);
	setMotorSpeed(rightMotor, 25);
	while(1){
		prevIntencity = intencity;
		intencity= getColorAmbient(colourSensor);
		displayBigTextLine(1, "%d", intencity);

		if (intencity > prevIntencity)
		{ //undo last action
			leftRight = !leftRight;
			if(leftRight == false){
				setMotorSpeed (leftMotor, 20);
				setMotorSpeed(rightMotor, 25);
			}
			else if(leftRight == true){
				setMotorSpeed (leftMotor, 25);
				setMotorSpeed(rightMotor, 20);
			}
		}
		if (intencity < prevIntencity)
		{ //carry on last action
			if(leftRight == false){
				setMotorSpeed (leftMotor, 20);
				setMotorSpeed(rightMotor, 25);
			}
			else if(leftRight == true){
				setMotorSpeed (leftMotor, 25);
				setMotorSpeed(rightMotor, 20);
			}
		}
	}



	/*else{

	//playSound(soundBeepBeep);
	setMotorSpeed(leftMotor, -10);
	setMotorSpeed(rightMotor, -10);
	displayBigTextLine(1, "BEEP");

	delay(2000);}*/
}
