#pragma config(Sensor, S1,     colSensor,      sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
/*//getColorReflected(S1); //gets reflected light from object 0-100

//getColorAmbient(S1); //gets ambient light from room 0-100

//getColorHue(S1);//gets colour hue 0-360

//getColorName(S1);// Color name	Enumerated Value

colorNone:	No object is detected by the color sensor	0
colorBlack:	A black object is detected by the color sensor	1
colorBlue:	A blue object is detected by the color sensor	2
colorGreen:	A green object is detected by the color sensor	3
colorYellow:	A yellow object is detected by the color sensor	4
colorRed:	A red object is detected by the color sensor	5
colorWhite:	A white object is detected by the color sensor	6
colorBrown:	A brown object is detected by the color sensor	7


	long red;
	long blue;
	long green;

getColorRGB(S1,red,green,blue);
displayCenteredTextLine(1, "Sensor Value: %d", red);//displays a sonsors value
displayCenteredTextLine(2, "Sensor Value: %d", blue);//displays a sonsors value
displayCenteredTextLine(3, "Sensor Value: %d", green);//displays a sonsors value

getColorSaturation(S1);//gets saturation 0-100 low to high
*/

getColorName(S1);// Color name	Enumerated Value
displayCenteredTextLine (1, "Sensor Value: %d", sensorValue[S1]);


}
}
