#pragma config(Sensor, S1,     colourSensor,   sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          motorL,        tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          motorR,        tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{

forward(1,rotations,100);


}
